### PR TITLE
Add a xhrSandbox test (close #87)

### LINKED ISSUE #87: Add a xhrSandbox test
I've found the test that relates to hammerhead:

```js
asyncTest('B238528 - Unexpected text modifying during typing text in the search input on the http://www.google.co.uk', function () {
    var timeout = 100;

    var ready = function () {
        if (this.readyState === this.DONE) {
            ok(syncActionExecuted);
            start();
        }
    };

    var syncActionExecuted = false;
    
    var xhr = new XMLHttpRequest();

    xhr.onreadystatechange = ready;
    xhr.open('GET', '/xhr-test/' + timeout);
    xhr.send(null);

    syncActionExecuted = true;
});
```

### PR DESCRIPTION
**Pull request by churkin**
\cc @AlexanderMoskovkin @miherlosev

### CODE REVIEW

**Comment by inikulin** [comment]
tests failing

**Comment by churkin** [comment]
passed now

**Comment by inikulin** [comment]
Let's just remove comment and we set.

\r-

**Comment by miherlosev** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Pull request merged**
