### PR TITLE
Update npm version to 1.0.0

### PR DESCRIPTION
**Pull request by churkin**
\cc @inikulin @AlexanderMoskovkin

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
There are two opened issues in the [v1.0.0 milestone](https://github.com/superroma/testcafe-hammerhead/milestones/v1.0.0), I suppose we should close them before update the version

**Comment by inikulin** [comment]
@AlexanderMoskovkin +1
\r-

**Comment by churkin** [comment]
Are all ready?

**Comment by inikulin** [comment]
One issue is still open: #158

**Comment by miherlosev** [comment]
#158 closed

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Pull request merged**
