### PR TITLE
JavaScript code in the onload attribute of the body tag is not processed (fix #33)

### LINKED ISSUE #33: JavaScript code in the onload attribute of the body tag is not processed
This issue occurs when passing the HTML code below to the Html.processHtml function:
```html
<head></head><body onload="var img = document.createElement('img'); img.src = 'http://some.com/img';"></body>
```

### PR DESCRIPTION
**Pull request by LavrovArtem**
/cc @churkin @miherlosev

### CODE REVIEW

**Comment by inikulin** [comment]
@LavrovArtem do not use whole repo name in the commit message. The issue ID is just enough.

**Comment by LavrovArtem** [comment]
@inikulin https://help.github.com/articles/closing-issues-via-commit-messages/#closing-an-issue-in-a-different-repository

**Comment by inikulin** [comment]
@LavrovArtem 

> To close an issue in **another repository**, use the username/repository#issue_number syntax, as described in "Writing on GitHub".

**Comment by LavrovArtem** [comment]
FPR

**Comment by churkin** [comment]
@LavrovArtem  Add description and code sample please

**Comment by inikulin** [comment]
Please add meaningful commit message

**Comment by inikulin** [comment]
\r-

**Comment by LavrovArtem** [comment]
FPR

**Comment by inikulin** [comment]
@LavrovArtem qunit tests fails

**Comment by churkin** [comment]
Add html tag to the test

**Comment by LavrovArtem** [comment]
FPR

**Comment by inikulin** [comment]
Can you rebase, pls (as far as I know @miherlosev landed a new test for this functionality a couple of days ago) ?

**Comment by LavrovArtem** [comment]
@inikulin already done

**Comment by inikulin** [comment]
lgtm, then

**Comment by inikulin** [comment]
ping @miherlosev

**Comment by miherlosev** [comment]
to @inikulin - merge commit from @LavrovArtem

**Pull request merged**
