### PR TITLE
Add comment (close #115)

### LINKED ISSUE #115: How uploading works on the Linux/MacOS platforms?
In the Hammerhead we are using windows-specific code:

`const FAKE_PATH_STRING         = 'C:\\fakepath\\';`

We should investigate how it works on other platforms.

### PR DESCRIPTION
**Pull request by LavrovArtem**

### CODE REVIEW

**Comment by inikulin** [comment]
Seems like bot is still broken \cc @AlexanderMoskovkin

**Comment by AlexanderMoskovkin** [comment]
The bot is ok. It's the `saucelabs environment error` on some virtual machines. It's a problem on the saucelabs side, we can't fix it

**Comment by inikulin** [comment]
@AlexanderMoskovkin But, shouldn't bot restart tests in that case?

**Comment by AlexanderMoskovkin** [comment]
Failed tests were restarted three times.

**Comment by inikulin** [comment]
Which delay was useb beetween restarts?

**Comment by AlexanderMoskovkin** [comment]
It was about 6 minutes between each rerun. If it's necessary we can increase the delay or reruns count when the saucelabs environment error appeared

**Comment by inikulin** [comment]
Yeah, I think we should use progressive delays as well.

**Comment by AlexanderMoskovkin** [comment]
ok

**Comment by inikulin** [comment]
lgtm

**Comment by churkin** [comment]
lgtm

**Pull request merged**
