### PR TITLE
 Get rid of 'async' in the qunit tests #24

### LINKED ISSUE #24: Get rid of 'async' in the qunit tests

### PR DESCRIPTION
**Pull request by miherlosev**
cc @inikulin  @churkin 
Close #24

### CODE REVIEW

**Comment by inikulin** [comment]
Why we have code required only for the testing purposes in our production code? Use Promises.

**Comment by inikulin** [comment]
\r-

**Comment by inikulin** [comment]
More likely you will need to refactor individual tests with promises, rather than introducing utility functions.

**Comment by inikulin** [comment]
@miherlosev Why close?

**Comment by miherlosev** [comment]
It is my error. When the task is complete, I will reopen the issue.

**Comment by inikulin** [comment]
Ok. You can fill another pull request then and **use feature-branches** to avoid such situations.

**Comment by miherlosev** [comment]
Ok

**Pull request closed without merging**
