### PR TITLE
IE11 throws an error when the second parameter of the Blob function is undefined (fix #44)

### LINKED ISSUE #44: IE11 throws an error when the second parameter of the Blob function is undefined
The issue occurs because we override the Blob function. If the overridden function is called with one parameter, it calls the original function with two parameters where the second parameter is undefined.

```javascript
new Blob(["a"])
```
Text of the error: "Could not complete the operation due to error 800a138f."

### PR DESCRIPTION
**Pull request by LavrovArtem**
/cc @inikulin @miherlosev

### CODE REVIEW

**Comment by LavrovArtem** [comment]
FPR

**Comment by inikulin** [comment]
It requires rebase now

**Comment by LavrovArtem** [comment]
FPR

**Comment by LavrovArtem** [comment]
FPR

**Comment by LavrovArtem** [comment]
FPR

**Comment by inikulin** [comment]
LGTM

**Comment by inikulin** [comment]
iOS tests timeouted

**Comment by AlexanderMoskovkin** [comment]
:white_check_mark: Tests for the commit b157b2ecfa1711c060b0c51c221859ebb3b87058 have passed. See [details](https://travis-ci.org/testcafe-build-bot/testcafe-hammerhead/builds/76113515).

Tests are ok now. We've found the issue with travis and saucelabs and will fix it in the gulp-qunit-harness. The problem appears when more than one travis tasks started in the one time.
So, @inikulin @miherlosev you can review the pr

**Comment by inikulin** [comment]
LGTM then

**Pull request merged**
