### PR TITLE
The URL attribute is set to an empty string on the client for the second time (T295078) (fix #159)

### LINKED ISSUE #159: The URL attribute is set to an empty string on the client for the second time (T295078)
That's why Firefox reloads the iframe and removes Hammerhead from it.

The Firefox scenario:

* an iframe without a src is being processed on the server
```html
<iframe src="" src-hammerhead-stored-value=""></iframe>
```
* ```window.Hammerhead``` is initialized in the iframe on the client
* ```src``` is again set to an empty string on the client
* the iframe is reloaded (i.e. ```window.Hammerhead``` is removed)
* finally, we try to execute the task script with eval() and get the ```TypeError: Hammerhead is undefined error```

### PR DESCRIPTION
**Pull request by LavrovArtem**
@inikulin @churkin

### CODE REVIEW

**Comment by inikulin** [comment]
lgtm

**Comment by churkin** [comment]
I do not see the test scenario

**Comment by inikulin** [comment]
@churkin @LavrovArtem Seems like I'm missing context. Can you issue more details in #159: repro example, expected and actual behaviors

**Comment by inikulin** [comment]
Odd, we are starting to get `module not found` errors in some PRs, \cc @AlexanderMoskovkin @churkin

**Comment by inikulin** [comment]
Guys, please try to reproduce npm install fails with node 10 locally (you can use [nvm](https://github.com/coreybutler/nvm-windows) for windows to switch versions). If it reproduces locally, seems like some of our transitive dependencies requires node 12 now. If so we need to abandon node 10 support, which requires some additional job and benefits: native promises, classes, generators, conts, built-in keep-alive user agent, etc.

**Comment by LavrovArtem** [comment]
FPR

**Comment by inikulin** [comment]
Lgtm

**Comment by churkin** [comment]
lgtm

**Pull request merged**
