### PR TITLE
Move xhr related tests from TestCafe to Hammerhead (close #109)

### LINKED ISSUE #109: Add tests for XhrSandbox
We should move some tests for `XhrSandbox` from the `TestCafe` project to the `Hammerhead`.  `xhrBarrier` is used in this tests, but just `XhrSandbox` functionality is tested, so we should get rid of `xhtBarrier` here

```js
asyncTest('Redirect requests to proxy', function () {
        expect(3);

        xhrBarrier.init();

        xhrBarrier.startBarrier(function () {
            start();
        });

        var action = function (callback) {
            $.get('/xhr-test/100', function (url) {
                strictEqual(url, '/sessionId/https://example.com/xhr-test/100');
            });

            $.get('http://' + window.location.host + '/xhr-test/200', function (url) {
                strictEqual(url, '/sessionId/https://example.com/xhr-test/200');
            });

            $.get('https://example.com/xhr-test/300', function (url) {
                strictEqual(url, '/sessionId/https://example.com/xhr-test/300');
            });
            callback();
        };

        action(function () {
            xhrBarrier.waitBarrier();
        });
    });

    asyncTest('Unsupported protocol', function () {
        var jqxhr = null;

        expect(1);

        xhrBarrier.init();

        var handler = function (err) {
            strictEqual(err.code, urlUtil.URL_UTIL_PROTOCOL_IS_NOT_SUPPORTED);
            xhrBarrier.events.off(xhrBarrier.XHR_BARRIER_ERROR, handler);
            start();
        };

        xhrBarrier.events.on(xhrBarrier.XHR_BARRIER_ERROR, handler);

        $.get('gopher:test.domain');
    });

    asyncTest('TC request in not processed by page processor', function () {
        var ready = function () {
            if (this.readyState === this.DONE)
                ok(this.responseText.indexOf(HH_CONST.DOM_SANDBOX_STORED_ATTR_POSTFIX) === -1);
        };

        expect(1);

        xhrBarrier.init();

        xhrBarrier.startBarrier(function () {
            HH_SETTINGS.SERVICE_MSG_URL = null;
            start();
        });

        HH_SETTINGS.SERVICE_MSG_URL = '/wrap-responseText-test/json';

        var xhr = new XMLHttpRequest();

        xhr.onreadystatechange = ready;
        xhr.open('GET', HH_SETTINGS.SERVICE_MSG_URL, false);
        xhr.send(null);

        xhrBarrier.waitBarrier();
    });
```

### PR DESCRIPTION
**Pull request by miherlosev**
/cc @inikulin @churkin

### CODE REVIEW

**Comment by inikulin** [comment]
lgtm @AlexanderMoskovkin  remove test from TC repo once this get merged

**Comment by AlexanderMoskovkin** [comment]
I will remove it with the https://github.com/superroma/testcafe-phoenix/issues/44 issue commit. I'm working on it right now

**Comment by inikulin** [comment]
lgtm

**Comment by churkin** [comment]
lgtm

**Pull request merged**
