### PR TITLE
Prepare code comments (#93). Part 1 - Client code. (also close #94)

### LINKED ISSUE #94: Rename `src/client/dom-processor/dom-processor.js` to the `src/client/dom-processor/index.js`
And require it as `./dom-processor` in client sources.

### PR DESCRIPTION
**Pull request by churkin**
\сс @VasilyStrelyaev @inikulin @LavrovArtem

### CODE REVIEW

**Comment by inikulin** [comment]
Linting failed

**Comment by inikulin** [comment]
lgtm

**Comment by LavrovArtem** [comment]
lgtm

**Comment by VasilyStrelyaev** [comment]
lgtm

**Pull request merged**
