### PR TITLE
Refactor Session, remove ShadowUI-related contants from shared const (partially implements refactorings suggested in #68 and #129)

### PR DESCRIPTION
**Pull request by inikulin**
\cc @churkin @miherlosev @LavrovArtem

### CODE REVIEW

**Comment by miherlosev** [comment]
lgtm

**Comment by churkin** [comment]
lgtm

**Comment by LavrovArtem** [comment]
lgtm

**Comment by LavrovArtem** [comment]
rebase pls

**Comment by inikulin** [comment]
FPR

**Comment by inikulin** [comment]
ping

**Comment by inikulin** [comment]
thx

**Pull request merged**
