### PR TITLE
add 'release' build option (close #23)

### LINKED ISSUE #23: Create 'debug' and 'release' build options
In the release mode we should uglify client scripts

### PR DESCRIPTION
**Pull request by miherlosev**
/cc @inikulin @LavrovArtem 

Usage
gulp rebuild --release

### CODE REVIEW

**Comment by miherlosev** [comment]
FPR

**Comment by LavrovArtem** [comment]
lgtm

**Comment by miherlosev** [comment]
Pull request contain  only the 'a3d996b' commit (with green tests) - see 'Commits' tab.

**Comment by miherlosev** [comment]
@inikulin  - FPR

**Comment by inikulin** [comment]
Something is really wrong with our build bot. \cc @AlexanderMoskovkin

**Comment by miherlosev** [comment]
FPR

**Comment by inikulin** [comment]
Can we configure Travis to run tests in release configuration? \cc @AlexanderMoskovkin

**Comment by inikulin** [comment]
@miherlosev Let's wait for @AlexanderMoskovkin. I would like to enable `release` configuration for the Travis.

**Comment by AlexanderMoskovkin** [comment]
Just add the `--release` argument in the [script field value](https://github.com/superroma/testcafe-hammerhead/blob/c48cc3ed819d548af2c63b119ee888efd2b5941c/package.json#L61) in package.json
`"test": "gulp travis --release"`

**Comment by miherlosev** [comment]
FPR

**Comment by inikulin** [comment]
lgtm

**Pull request merged**
