### PR TITLE
change library for Promise to es6-promise (server-side)

### PR DESCRIPTION
**Pull request by miherlosev**
cc @inikulin

### CODE REVIEW

**Comment by miherlosev** [comment]
Will be fixed after merge https://github.com/superroma/testcafe-hammerhead/pull/41

**Comment by inikulin** [comment]
Ok, let's wait for #41 and then rebase.

**Comment by miherlosev** [comment]
FRP

**Comment by miherlosev** [comment]
FRP

**Comment by inikulin** [comment]
It requires rebase now

**Comment by AlexanderMoskovkin** [comment]
:white_check_mark: Tests for the commit 0495b73e7351ba5abddec91cff68cdac83fbeb78 have passed. See [details](https://travis-ci.org/testcafe-build-bot/testcafe-hammerhead/builds/76111854).

Tests are ok. We've found the issue with travis and saucelabs and will fix it in the gulp-qunit-harness. The problem appears when more than one travis tasks started in the one time.
So, @inikulin we can review the pr

**Comment by inikulin** [comment]
LGTM then

**Comment by AlexanderMoskovkin** [comment]
LGTM

**Pull request merged**
