### PR TITLE
add 'Microsofr Edge' to SauceLabs' test browsers

### PR DESCRIPTION
**Pull request by miherlosev**

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
Hmm, I see the `ERROR: Can not create the report:` error in the tests log after MSEdge added. I'll research this

**Comment by AlexanderMoskovkin** [comment]
I've found the issue with MS Edge related to saucelabs rest api. I've handled it in the qunit-harness@0.1.22
I'll restart the tests

**Comment by AlexanderMoskovkin** [comment]
Tests for the commit 6dd89945c31f4645517ef833511defe324bb07f4 have passed. See [details](https://travis-ci.org/testcafe-build-bot/testcafe-hammerhead/jobs/78546219).

**Comment by miherlosev** [comment]
FPR
\cc @churkin @LavrovArtem

**Comment by churkin** [comment]
lgtm

**Comment by LavrovArtem** [comment]
lgtm

**Pull request merged**
