### PR TITLE
eslint: added "no-undef" rule

### PR DESCRIPTION
**Pull request by LavrovArtem**
/cc @churkin @AlexanderMoskovkin

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
@LavrovArtem Are you sure about the commit and pr naming? I see you fix some functionality with document.URL in the commit, and eslint rule is not the most important thing here

**Comment by LavrovArtem** [comment]
Yes i am sure, the fixing of some functionality is a consequence for adding the ```no-undef``` rule

**Comment by AlexanderMoskovkin** [comment]
How I see: there was the bug in the code, ElementEditingWatcher was not defined.
You've fixed the problem, written the test for it and add the eslint rule to avoid such problem in the future. Is this true?
If yes, I suppose, the main point - you've fixed the bug with js error. /cc @churkin

**Comment by LavrovArtem** [comment]
[tests passed](https://travis-ci.org/testcafe-build-bot/testcafe-hammerhead/jobs/78369391)

**Pull request closed without merging**
