### PR TITLE
The messageSandbox pingIFrame function doesn't work (close #86)

### LINKED ISSUE #86: The messageSandbox pingIFrame function doesn't work
The issue appeared in the https://github.com/superroma/testcafe-hammerhead/commit/67d00b7a7de729cf84cbb889e363a9bac644d703 commit

Look at the [`pingIFrame` function](https://github.com/superroma/testcafe-hammerhead/blob/master/src/client/sandbox/message.js#L180)

There are `pingInterval, pingTimeout` vars and `this.pingInterval, this.pingTimeout` members. We should stay one of these.
Now you call `this.pingTimeout = NativeMethods.setTimeout.call` but `this.window.clearTimeout(pingTimeout);`

And I suppose we should have a test for this

### PR DESCRIPTION
**Pull request by churkin**
\cc @inikulin @AlexanderMoskovkin

### CODE REVIEW

**Comment by inikulin** [comment]
Tests for this?

**Comment by churkin** [comment]
FPR

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by inikulin** [comment]
lgtm

**Pull request merged**
