### PR TITLE
Hammerhead.wrapDomAccessors doesn't work (close #80)

### LINKED ISSUE #80: Hammerhead.wrapDomAccessors doesn't work
You can see the problem in the following server test:
```js
var hammerhead  = require('../../lib');
var jsProcessor = require('../../lib/processing/js');
var expect        = require('chai').expect;

describe('wrapDomAccessors', function () {
    it('Should work via jsProcessor', function () {
        expect(jsProcessor.process('anything')).eql('anything');    // ---> ok
    });

    it('Should work via hammerhead api', function () {
        expect(hammerhead.wrapDomAccessors('anything')).eql('anything');    // ---> TypeError: undefined is not a function
    });
});
```

It fails in the `processing\js\index.js` file in the `process` method because of incorrect context (`this.isJSON(code);`)

### PR DESCRIPTION
**Pull request by churkin**
\cc @inikulin @AlexanderMoskovkin

### CODE REVIEW

**Comment by inikulin** [comment]
What's going on with the tests?

**Comment by AlexanderMoskovkin** [comment]
Tests for the commit 0681a3db295e0ac11bd3194608381bce3a03907b have passed. See [details](https://travis-ci.org/testcafe-build-bot/testcafe-hammerhead/builds/80440088).

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by inikulin** [comment]
lgtm

**Pull request merged**
