### PR TITLE
fix script error: Uncaught TypeError: _shadowUi.onBodyElementMutation is not a function ( closes #96)

### LINKED ISSUE #96: Script error: Uncaught TypeError: _shadowUi.onBodyElementMutation is not a function
The following code produces the script error  - 'Uncaught TypeError: _shadowUi.onBodyElementMutation is not a function'

```javascript
var html = document.documentElement;
var body = document.getElementsByTagName('body')[0];
html.insertBefore(body, html.firstChild);
```

### PR DESCRIPTION
**Pull request by miherlosev**
/cc @inikulin @churkin

### CODE REVIEW

**Comment by inikulin** [comment]
\cc @churkin ?

**Comment by miherlosev** [comment]
FPR

**Comment by inikulin** [comment]
lgtm

**Comment by miherlosev** [comment]
I will add more test scenarious.

**Comment by miherlosev** [comment]
FPR

**Comment by churkin** [comment]
lgtm

**Comment by inikulin** [comment]
lgtm

**Pull request merged**
