### PR TITLE
Refactor the structure of the client sandboxes (close #17)

### LINKED ISSUE #17: Refactor the structure of the client sandboxes
\cc @LavrovArtem @miherlosev 

Based on https://github.com/superroma/testcafe-hammerhead/issues/5

- [ ] Exclude 'sandboxes' entity to the 'sandboxes.js' file
- [ ] Simplify dom sandbox to the node sandbox
- [ ] Make "sandboxes" entity a point of entry for all sandboxes
- [ ] Rename `sandboxes` to `sandbox`
- [ ] Get rid of `init` methods and use ctors instead
- [ ] Let main sandbox construct other parts and pass instances to the ctors instead of `require`-approach.

### PR DESCRIPTION
**Pull request by churkin**
\cc @AlexanderMoskovkin @inikulin @miherlosev

### CODE REVIEW

**Comment by churkin** [comment]
Tests passed https://travis-ci.org/churkin/testcafe-hammerhead

**Comment by miherlosev** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by inikulin** [comment]
niccceee!

**Pull request merged**
