### PR TITLE
Use the native XMLHttpRequest instead of a SERVICE_MSG_REQUEST_FLAG flag mechanism (fix #113)

### LINKED ISSUE #113: Use the native XMLHttpRequest instead of a SERVICE_MSG_REQUEST_FLAG flag mechanism
@inikulin wrote:
>We have a SERVICE_MSG_REQUEST_FLAG in https://github.com/churkin/testcafe->hammerhead/blob/es6/src/client/sandbox/xhr/index.js . It was used to skip tracking of the transport >messages. I'm wondering, since we use native methods now, do we still need this flag?

### PR DESCRIPTION
**Pull request by LavrovArtem**
/cc @inikulin @churkin

### CODE REVIEW

**Comment by inikulin** [comment]
linting failed

**Comment by LavrovArtem** [comment]
FPR

**Comment by inikulin** [comment]
lgtm

**Comment by churkin** [comment]
lgtm

**Pull request merged**
