### PR TITLE
Health monitor fix

### PR DESCRIPTION
**Pull request by churkin**
\cc @inikulin @LavrovArtem

### CODE REVIEW

**Comment by inikulin** [comment]
Wow, things with SauceLabs got from bad to worse. @AlexanderMoskovkin take a look, please

**Comment by AlexanderMoskovkin** [comment]
There's nothing new. I'm working on it

**Comment by inikulin** [comment]
Good

**Comment by AlexanderMoskovkin** [comment]
:white_check_mark: Tests for the commit e4d6d8d952d7f553310f27515a10360011b61d74 have passed. See [details](https://travis-ci.org/testcafe-build-bot/testcafe-hammerhead/jobs/77479958).

**Comment by churkin** [comment]
Merge please

**Comment by inikulin** [comment]
lgtm

**Pull request merged**
